### ISSUE TITLE
no slider i homeassistant

### ISSUE THREAD

**Issue by dartfrogdk** [nordeep/esphome_fan_controller#2]
i cant get the slider in homeassistant, im using your esphome setup, do you know what can be wrong

**Comment by zettalion** [comment]
Hey - I had a similar issue when I flashed this ECU using ESPhome.   Home assistant "found it", but then in the autodetected integrations Home Assistant it "disappeared".   All i needed to do was reboot home assistant and the new "fan controller ECU was found", i added it right away, and then all the native sensors and fan speed commands showed up as required (including the slider).   Did you get yours working?

**Comment by dartfrogdk** [comment]
No i cant get it to work

Den man. 28. feb. 2022 kl. 21.21 skrev Foosman ***@***.***>:

**Comment by nordeep** [comment]
Slider is the default control available in Integrations -> ESPHome device page. 
You need to make sure you add device integration after flashing ESP and connected to WiFi.
