### ISSUE TITLE
pwn logical level is 5V?

### ISSUE THREAD

**Issue by 0neday** [nordeep/esphome_fan_controller#3]
I use `3.3v `, it could control fan speed, but can not stop fan.

so, it must have  a logical level converter to convert `3.3 v`to `5v`

But, when I use 5v to drive fan, and use 3.3v pwn signal to control fan, that could work fine.

**Comment by nordeep** [comment]
Yes. PWM logic level on fan is 5V.

**Comment by 0neday** [comment]
thx
