### ISSUE TITLE
Wemos D1 mini doesnot power up

### ISSUE THREAD

**Issue by goxofy** [nordeep/esphome_fan_controller#4]
Hi thanks @nordeep ,
I have a 4-pin pwm fan and I connected the wire follow the schema picture,but my wemos di mini doesn't work, it seems like doesn't power up , I measured the 5v and GND pin voltage of the d1 mini with a voltmeter and it showed 0v, so did I do something wrong?
Thanks again.

**Comment by nordeep** [comment]
You need to power up Wemos from separate PSU. Micro USB +5V or direct +3.3V
to Wemos pins.

чт, 18 авг. 2022 г., 05:30 TinK ***@***.***>:

**Comment by goxofy** [comment]
Hi @nordeep 
I understant now!
But if I want to use direct +3.3V, what shoud I do?
Could I connect the separate +3.3V and GND to the Wemos 3.3V and GND Pin?

**Comment by nordeep** [comment]
Yes, you have to power up Wemos by connecting +3.3V and GND.

чт, 18 авг. 2022 г. в 09:53, TinK ***@***.***>:

**Comment by goxofy** [comment]
@nordeep But in the diagram, the +3.3V and GND has connected to the Logic Level Converter and MOSFET VCC, shoud I connect the PSU with this together?

**Comment by nordeep** [comment]
No, better is to power Wemos D1 through onboard micro usb.
But, if you want to power up Wemos by +3.3V you always may done this by
connect you +3.3 PSU to Wemos pins.

чт, 18 авг. 2022 г., 11:24 TinK ***@***.***>:

**Comment by goxofy** [comment]
OK Thank you very much

**Comment by goxofy** [comment]
Hi @nordeep ,

I have another question about the software part, my fan is a 60W(12V 5A) violence fan with 13000 RPM, I use a 72W(12V. 6A) power supply for it, now it seems like works but the blade only shake a liitle and then stoped when I press Turn_ON  button, should I change the yaml code to correct it?

**Comment by nordeep** [comment]
It seems you need to adjust PWM frequency but it's better to read datasheet for your fan.

**Comment by goxofy** [comment]
> It seems you need to adjust PWM frequency but it's better to read datasheet for your fan.

ok thanks a lot
